@startuml RVSQ-UC-13_3_Verification_Integrite
left to right direction
actor "Citoyen" as a1

package "Plateforme RVSQ" {
  usecase "RVSQ-UC-13.3 : Vérification d’intégrité" as UC133
  usecase "Valider signature" as UC133_1
  usecase "Contrôler horodatage" as UC133_2
  usecase "Accepter/Refuser message" as UC133_3
}

package "Systèmes Externes" {
  
}

a1 --> UC133

UC133 ..> UC133_1 : <<include>>
UC133 ..> UC133_2 : <<include>>
UC133 ..> UC133_3 : <<include>>

note top of UC133
Vérifier l’intégrité des messages et rejeter toute altération.
end note

note bottom of UC133
Caractéristique associée : CAR13
end note
@enduml